# Inspired from Sea Bass blog and github files

FROM nvidia_noetic_ros:latest
SHELL ["/bin/bash", "-c"]

# This part is from below link:
# https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user
# ********************************************************
ARG USERNAME=areza
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
# ********************************************************

# Installing some basic apps
RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends git tmux

# Setup the ArduPilot SITL
RUN mkdir /home/${USERNAME}/repositories \
  && git clone https://github.com/ArduPilot/ardupilot.git /home/${USERNAME}/repositories/ardupilot

RUN cd /home/${USERNAME}/repositories/ardupilot \
  && git submodule update --init --recursive

RUN /home/${USERNAME}/repositories/ardupilot/Tools/environment_install/install-prereqs-ubuntu.sh -y
RUN export PATH="/home/${USERNAME}/repositories/ardupilot/Tools/autotest:$PATH"

