import rospy
from mavros_msgs.msg import ParamValue
from mavros_msgs.srv import ParamSet, ParamSetResponse, ParamSetRequest, ParamGet, ParamGetRequest, ParamGetResponse
from pymavlink import mavutil

from RfCommunication.Job.Interface.JobInterface import JobInterface
from RfCommunication.RfConnection.ConnectionInterface.ConnectionInterface import ConnectionInterface


class param_set_job(JobInterface):
    _paramSetProxy = None
    _paramGetProxy = None

    def __init__(self, message, rfConnection: ConnectionInterface, system, component):
        """

        @type message: MAVLink_param_set_message
        """
        super().__init__(message, rfConnection, system, component)

        if (param_set_job._paramSetProxy is None) and self._isSystemMavrosSide():
            rospy.wait_for_service("/mavros/param/set")
            param_set_job._paramSetProxy = rospy.ServiceProxy("/mavros/param/set", ParamSet)

        if (param_set_job._paramGetProxy is None) and self._isSystemMavrosSide():
            rospy.wait_for_service("/mavros/param/get")
            param_set_job._paramGetProxy = rospy.ServiceProxy("/mavros/param/get", ParamGet)

        self._request = self._createRequest()
        self._response = ParamSetResponse()
        return

    def _doJob(self):
        if self._isSystemMavrosSide():
            self._response = param_set_job._paramSetProxy(self._request)
            rospy.loginfo(f"Success: {self._response.success}.")
        return

    def _createRequest(self) -> ParamSetRequest:
        request = ParamSetRequest()
        request.param_id = self.getMessage().param_id
        # Initialize ParamValue fields based on the parameter value coming from autopilot, since in the list of params
        # generated by the ardupilot scripts, their types are not specified, we can evaluate their types by checking the
        # value coming from the autopilot.
        # 1. get the param from the autopilot
        paramGetResponse: ParamGetResponse = param_set_job._paramGetProxy(
            ParamGetRequest(param_id=self.getMessage().param_id))
        # 2. check its type and Set the corresponding field of the 'request.value' based on its type.
        if paramGetResponse.value.integer != 0:
            request.value = ParamValue(integer=self.getMessage().param_value)
        elif paramGetResponse.value.real != 0.0:
            request.value = ParamValue(real=self.getMessage().param_value)
        else:
            request.value = ParamValue()
        return request

    def _isSystemMavrosSide(self):
        """
        @return: This function returns True if RfCommunicationHandler is created in the system connected to the
        autopilot via mavros node. So the wait for mavros service does not block the code.
        """
        return mavutil.mavlink.MAV_TYPE_FIXED_WING == self._system and 1 == self._component
